name: flutter_stasis_example
description: Example app for the flutter_stasis ecosystem.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"  
  flutter: ">=3.27.0" 

dependencies:
  flutter:
    sdk: flutter
  flutter_stasis:
    path: ../packages/flutter_stasis
  equatable: ^2.0.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_stasis_test:
    path: ../packages/flutter_stasis_test
  flutter_lints: ^3.0.0