name: flutter_stasis

packages:
  - packages/*
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart run melos exec --fail-fast -- dart analyze --fatal-infos
    description: Analyze all packages.

  format:
    run: dart run melos exec -- dart format . --set-exit-if-changed
    description: Check formatting across all packages.

  test:dart:
    run: dart run melos exec --fail-fast --no-flutter --dir-exists=test -- dart test
    description: Run tests in pure Dart packages.

  test:flutter:
    run: dart run melos exec -c 1 --fail-fast --flutter --dir-exists=test -- flutter test
    description: Run tests in Flutter packages.

  test:
    run: dart run melos run test:dart --no-select && dart run melos run test:flutter --no-select
    description: Run tests in all packages that have a test directory.

  publish:dry:
    run: dart run melos exec -c 1 --fail-fast --order-dependents --no-private -- dart pub publish --dry-run
    description: Dry-run publish for all packages.

  publish:all:
    run: dart run melos exec -c 1 --fail-fast --order-dependents --no-private -- dart pub publish --force
    description: Publish all packages to pub.dev.
