name: flutter_stasis_test
description: "Test helpers for flutter_stasis. captureStates, captureEvents, assertStateSequence and assertEventSequence."
version: 0.3.1
homepage: https://github.com/DIMAAGR/flutter_stasis
repository: https://github.com/DIMAAGR/flutter_stasis

topics:
  - testing
  - state-management
  - flutter

environment:
  sdk: ^3.10.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stasis: ^0.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
